services:
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - '1883:1883'
    volumes:
      - mqtt_data:/mosquitto/data
      - mqtt_log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  mongodb:
    image: mongo:focal
    ports:
      - '27017:27017'
    restart: unless-stopped

  playnite-web:
    image: ghcr.io/andrew-codes/playnite-web-app:latest
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - HOST=localhost
      - DB_HOST=mongodb
      - DB_PORT=27017
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
    volumes:
      - playnite_assets:/opt/playnite-web-app/public/assets/asset-by-id
    depends_on:
      - mqtt
      - mongodb
    restart: unless-stopped

volumes:
  mqtt_data:
  mqtt_log:
  playnite_assets:
