services:
  db:
    image: postgres:13.22
    ports:
      - '5432:5432'
    envrironment:
      - POSTGRES_USER={{db_user}}
      - POSTGRES_PASSWORD={{db_password}}
    restart: unless-stopped

  playnite-web:
    image: ghcr.io/andrew-codes/playnite-web-app:latest
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - HOST=localhost
      - DB_URL=postgres://{{db_user}}:{{db_password}}@games:5432?schema=public
    volumes:
      - playnite_assets:/opt/playnite-web-app/public/assets/game-assets
    depends_on:
      - db
    restart: unless-stopped

volumes:
  playnite_assets:
