nodeLinker: pnp

packageExtensions:
  "@remix-pwa/dev@*":
    dependencies:
      "@remix-pwa/worker-runtime": "*"
      glob: "*"
  "@remix-pwa/worker-runtime@*":
    dependencies:
      "@remix-run/server-runtime": "*"
  "@remix-run/dev@*":
    dependencies:
      "@remix-run/react": "*"
      react: "*"
      react-dom: "*"
  remix-auth-form@*:
    dependencies:
      "@remix-run/server-runtime": "*"
  remix-auth@*:
    dependencies:
      "@remix-run/server-runtime": "*"
  remix-island@*:
    dependencies:
      "@remix-run/server-runtime": "*"
  remix-routes@*:
    dependencies:
      "@vercel/remix-run-dev": "*"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.3.0.cjs
