cacheFolder: .yarn/cache

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  '@apollo/client-react-streaming@*':
    dependencies:
      'graphql': '*'
  '@prisma/client@*':
    dependencies:
      prisma: '*'
  ts-jest@*:
    dependencies:
      jest-util: '*'
  'cypress@*':
    dependencies:
      react: '*'
      react-dom: '*'
  'jest@*':
    dependencies:
      'ts-node': '*'
  'jest-config@*':
    dependencies:
      'ts-node': '*'

pnpEnableEsmLoader: true

pnpMode: strict

supportedArchitectures:
  cpu:
    - current
    - x64
    - ia32
    - arm64
  libc:
    - glibc
  os:
    - current
    - linux
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-4.9.3.cjs
