cacheFolder: .yarn/cache

enableGlobalCache: false

nodeLinker: node-modules
pnpMode: strict

packageExtensions:
  '@remix-run/dev@*':
    dependencies:
      '@remix-run/react': '*'
      react: '*'
      react-dom: '*'
  cypress@*:
    dependencies:
      react: ^18.3.1
      react-dom: ^18.3.1
  remix-auth-form@*:
    dependencies:
      '@remix-run/server-runtime': '*'
  remix-auth@*:
    dependencies:
      '@remix-run/server-runtime': '*'
  remix-island@*:
    dependencies:
      '@remix-run/server-runtime': '*'
  remix-routes@*:
    dependencies:
      '@vercel/remix-run-dev': '*'
  '@mapbox/node-pre-gyp@*':
    dependencies:
      'nock': '*'
      'aws-sdk': '*'
      'mock-aws-s3': '*'
  'nock@*':
    dependencies:
      'mock-aws-s3': '*'
  "@prisma/client@*":
    dependencies:
      prisma: "*"

pnpEnableEsmLoader: true

supportedArchitectures:
  cpu:
    - current
    - x64
    - ia32
    - arm64
  libc:
    - glibc
  os:
    - current
    - linux
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-4.6.0.cjs
