cacheFolder: .yarn/cache

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  '@remix-run/dev@*':
    dependencies:
      '@remix-run/react': '*'
      react: '*'
      react-dom: '*'
  cypress@*:
    dependencies:
      react: ^18.3.1
      react-dom: ^18.3.1
  remix-auth-form@*:
    dependencies:
      '@remix-run/server-runtime': '*'
  remix-auth@*:
    dependencies:
      '@remix-run/server-runtime': '*'
  remix-island@*:
    dependencies:
      '@remix-run/server-runtime': '*'
  remix-routes@*:
    dependencies:
      '@vercel/remix-run-dev': '*'

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.3.1.cjs
