pnpEnableEsmLoader: true
packageExtensions:
  '@remix-run/dev@*':
    dependencies:
      '@remix-run/react': '*'
      'react-dom': '*'
      'react': '*'
  'remix-routes@*':
    dependencies:
      '@vercel/remix-run-dev': '*'
  'remix-island@*':
    dependencies:
      '@remix-run/server-runtime': '*'
  'remix-auth@*':
    dependencies:
      '@remix-run/server-runtime': '*'
  'remix-auth-form@*':
    dependencies:
      '@remix-run/server-runtime': '*'
  '@remix-pwa/dev@*':
    dependencies:
      'glob': '*'
      '@remix-pwa/worker-runtime': '*'
  '@remix-pwa/worker-runtime@*':
    dependencies:
      '@remix-run/server-runtime': '*'
