enableGlobalCache: true

nodeLinker: node-modules

packageExtensions:
  '@apollo/client-react-streaming@*':
    dependencies:
      graphql: '*'
  '@prisma/client@*':
    dependencies:
      prisma: '*'
  cypress@*:
    dependencies:
      react: '*'
      react-dom: '*'
  jest-config@*:
    dependencies:
      ts-node: '*'
  jest@*:
    dependencies:
      ts-node: '*'
  ts-jest@*:
    dependencies:
      jest-util: '*'

pnpEnableEsmLoader: true

pnpMode: strict

supportedArchitectures:
  cpu:
    - current
    - x64
    - ia32
    - arm64
  libc:
    - glibc
  os:
    - current
    - linux
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-4.10.3.cjs
