pnpEnableEsmLoader: true
packageExtensions:
  '@remix-run/dev@*':
    dependencies:
      '@remix-run/react': '*'
      'react-dom': '*'
      'react': '*'
  'remix-routes@*':
    dependencies:
      '@vercel/remix-run-dev': '*'
