name: "Deploy to Production"

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run all Verifications/Tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Read Node version
        run: echo "##[set-output name=NODE_VERSION;]$(cat package.json | jq .engines.node | sed -e 's/"//g' | sed -e 's/>=//g')"
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NODE_VERSION }}"
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.403"
      - name: Install deps
        run: yarn
      - name: Prepare
        run: yarn nx run-many --target=prepare --parallel --all
        env:
          ONEPASSWORD_TOKEN: ${{ secrets.ONEPASSWORD_TOKEN }}
          ONEPASSWORD_SERVER_URL: ${{ secrets.ONEPASSWORD_SERVER_URL }}
          ONEPASSWORD_VAULT_ID: ${{ secrets.ONEPASSWORD_VAULT_ID }}
      - name: Run all unit tests
        run: yarn nx run-many --target=test/unit --all --parallel

  deploy:
    name: Deploy Affected Apps
    runs-on: self-hosted
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Read Node version
        run: echo "##[set-output name=NODE_VERSION;]$(cat package.json | jq .engines.node | sed -e 's/"//g' | sed -e 's/>=//g')"
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NODE_VERSION }}"
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.403"
      - name: Install deps
        run: yarn
      - name: Prepare
        run: yarn nx run-many --target=prepare --parallel --all
        env:
          ONEPASSWORD_TOKEN: ${{ secrets.ONEPASSWORD_TOKEN }}
          ONEPASSWORD_SERVER_URL: ${{ secrets.ONEPASSWORD_SERVER_URL }}
          ONEPASSWORD_VAULT_ID: ${{ secrets.ONEPASSWORD_VAULT_ID }}
      - name: Deploy affected apps
        run: yarn nx affected --target=deploy --parallel --base=HEAD~ --head=HEAD --verbose
        env:
          CODECOV_TOKEN: ${{ secrets.CODE_COV_TOKEN }}
          ONEPASSWORD_TOKEN: ${{ secrets.ONEPASSWORD_TOKEN }}
          ONEPASSWORD_SERVER_URL: ${{ secrets.ONEPASSWORD_SERVER_URL }}
          ONEPASSWORD_VAULT_ID: ${{ secrets.ONEPASSWORD_VAULT_ID }}
          MQTT_HOST: ${{ secrets.K8S_MAIN_NODE_IP }}
          MQTT_PORT: ${{ secrets.MQTT_PORT_EXTERNAL }}
          MQTT_USERNAME: ${{ secrets.MQTT_USERNAME }}
          MQTT_PASSWORD: ${{ secrets.MQTT_PASSWORD }}
          NODE_ENV: production
