name: 'Remove Pull Request Packages'

on:
  pull_request:
    types: [closed]

permissions:
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  retention_policy:
    if: github.event.pull_request.merged == true
    name: Retention policy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          owner: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          package-type: container
          package-name: ${{ env.REGISTRY }}/${{ github.repository }}
          ignore-versions: '^([a-z0-9]+-v[0-9]+\.[0-9]+\.[0-9]+)|([a-z0-9]+-PR(?!${{ github.event.pull_request.number }})|([a-z0-9]+-dev))$]'
