name: 'Remove Pull Request Packages'

on:
  pull_request:
    types: [closed]

permissions:
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  retention_policy:
    if: github.event.pull_request.merged == true
    name: Retention policy
    runs-on: ubuntu-latest
    steps:
      - uses: smartsquaregmbh/delete-old-packages@v0.7.0
        with:
          user: andrew-codes
          type: container
          version-pattern: '^PR${{ github.event.pull_request.number }}$' # The regex needs to be escaped!
          names: |
            "*"
