name: 'Remove Pull Request Packages'

on:
  pull_request:
    types: [closed]

permissions:
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  retention_policy:
    if: github.event.pull_request.merged == true
    name: Retention policy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-version-ids: PR${{ github.event.pull_request.number }}
          package-name: ${{ github.repository }}-*
          package-type: container
          ignore-versions: '^(dev)|([0-9])'
          token: ${{ secrets.PACKAGE_PRUNER_TOKEN }}
