name: 'Remove Pull Request Packages'

on:
  pull_request:
    types: [closed]

permissions:
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  retention_policy:
    if: github.event.pull_request.merged == true
    name: Retention policy
    runs-on: ubuntu-latest
    steps:
      - uses: snok/container-retention-policy@v2
        with:
          image-names: '*'
          cut-off: two hours ago UTC+4
          timestamp-to-use: updated_at
          account-type: personal
          token: ${{ secrets.PACKAGE_PRUNER_TOKEN }}
          filter-tags: PR${{ github.event.pull_request.number }}
      - uses: snok/container-retention-policy@v2
        with:
          image-names: '*'
          cut-off: two hours ago UTC+4
          timestamp-to-use: updated_at
          account-type: personal
          token: ${{ secrets.PACKAGE_PRUNER_TOKEN }}
          untagged-only: true
